// Reads photos.json (generated by the GitHub Actions sync workflow) and
// populates the home page image and/or the gallery carousel, depending
// on which elements exist on the current page.

(async function () {
  let data = { homePagePic: null, gallery: [] };

  try {
    // Cache-bust so a freshly committed photos.json is picked up on reload
    const resp = await fetch("photos.json?v=" + Date.now());
    if (resp.ok) {
      data = await resp.json();
    }
  } catch (err) {
    console.error("Could not load photos.json:", err);
  }

  // ---- Home page picture ----
  const homePic = document.getElementById("home-pic");
  if (homePic && data.homePagePic) {
    homePic.src = data.homePagePic;
    homePic.hidden = false;
  }

  // ---- Gallery carousel ----
  const carousel = document.getElementById("carousel");
  if (carousel) {
    const photos = Array.isArray(data.gallery) ? data.gallery : [];
    const emptyMsg = document.getElementById("carousel-empty");

    if (photos.length === 0) {
      if (emptyMsg) emptyMsg.hidden = false;
      return;
    }

    const track = document.getElementById("carousel-track");
    const counter = document.getElementById("carousel-counter");
    const STAGE_RATIO = 5 / 3; // keep in sync with #carousel-stage CSS
    let index = 0;

    // One slide per photo; sliding the track gives the horizontal
    // transition between photos.
    for (const src of photos) {
      const slide = document.createElement("div");
      slide.className = "carousel-slide";
      const img = document.createElement("img");
      img.alt = "";
      img.onload = () => {
        // Photos wider than the stage get cropped to fill it exactly
        if (img.naturalWidth / img.naturalHeight > STAGE_RATIO) {
          img.classList.add("crop");
        }
      };
      img.src = src;
      slide.appendChild(img);
      track.appendChild(slide);
    }

    function show(i) {
      index = (i + photos.length) % photos.length; // wrap around
      track.style.transform = "translateX(" + (-index * 100) + "%)";
      counter.textContent = " " + (index + 1) + " of " + photos.length + " ";
    }

    document.getElementById("carousel-prev")
      .addEventListener("click", () => show(index - 1));
    document.getElementById("carousel-next")
      .addEventListener("click", () => show(index + 1));

    carousel.hidden = false;
    show(0);
  }
})();
