// Reads photos.json (generated by the GitHub Actions sync workflow) and
// populates the home page image and/or the gallery carousel, depending
// on which elements exist on the current page.

(async function () {
  let data = { homePagePic: null, gallery: [] };

  try {
    // Cache-bust so a freshly committed photos.json is picked up on reload
    const resp = await fetch("photos.json?v=" + Date.now());
    if (resp.ok) {
      data = await resp.json();
    }
  } catch (err) {
    console.error("Could not load photos.json:", err);
  }

  // ---- Home page picture ----
  const homePic = document.getElementById("home-pic");
  if (homePic && data.homePagePic) {
    homePic.src = data.homePagePic;
    homePic.hidden = false;
  }

  // ---- Gallery carousel ----
  const carousel = document.getElementById("carousel");
  if (carousel) {
    const photos = Array.isArray(data.gallery) ? data.gallery : [];
    const emptyMsg = document.getElementById("carousel-empty");

    if (photos.length === 0) {
      if (emptyMsg) emptyMsg.hidden = false;
      return;
    }

    const track = document.getElementById("carousel-track");
    const counter = document.getElementById("carousel-counter");
    const STAGE_RATIO = 5 / 3; // keep in sync with #carousel-stage CSS
    const count = photos.length;

    function makeSlide(src) {
      const slide = document.createElement("div");
      slide.className = "carousel-slide";
      const img = document.createElement("img");
      img.alt = "";
      img.onload = () => {
        // Photos wider than the stage get cropped to fill it exactly
        if (img.naturalWidth / img.naturalHeight > STAGE_RATIO) {
          img.classList.add("crop");
        }
      };
      img.src = src;
      slide.appendChild(img);
      return slide;
    }

    // Circular wrap: a clone of the last photo sits before the first,
    // and a clone of the first sits after the last. Track positions run
    // 0..count+1 with real photo i at position i+1. Wrapping slides onto
    // a clone in the clicked direction, then invisibly snaps to the
    // matching real slide once the animation ends.
    track.appendChild(makeSlide(photos[count - 1]));
    for (const src of photos) track.appendChild(makeSlide(src));
    track.appendChild(makeSlide(photos[0]));

    let pos = 1;

    function place() {
      track.style.transform = "translateX(" + (-pos * 100) + "%)";
      const shown = ((pos - 1) % count + count) % count;
      counter.textContent = " " + (shown + 1) + " of " + count + " ";
    }

    function jump(p) { // reposition without animating
      track.style.transition = "none";
      pos = p;
      place();
      track.offsetHeight; // flush layout so the next move transitions
      track.style.transition = "";
    }

    function normalize() { // resting on a clone? snap to its real slide
      if (pos === count + 1) jump(1);
      else if (pos === 0) jump(count);
    }

    // Snap as soon as the wrap animation finishes; the click handlers
    // also normalize first, covering rapid clicks and reduced-motion
    // (where no transitionend ever fires).
    track.addEventListener("transitionend", (e) => {
      if (e.target === track) normalize();
    });

    document.getElementById("carousel-prev")
      .addEventListener("click", () => { normalize(); pos -= 1; place(); });
    document.getElementById("carousel-next")
      .addEventListener("click", () => { normalize(); pos += 1; place(); });

    carousel.hidden = false;
    jump(1);
  }

  // ---- Warm every site photo ----
  // Whichever page is opened first fetches all photos (home + gallery),
  // so the other page's photos are already in the browser cache when
  // the visitor navigates there. References are kept on window so the
  // decoded images stay held for the life of the page.
  const everyPhoto = [data.homePagePic]
    .concat(Array.isArray(data.gallery) ? data.gallery : [])
    .filter(Boolean);
  window.warmPhotos = everyPhoto.map((src) => {
    const img = new Image();
    img.src = src;
    return img;
  });
})();
