// Reads photos.json (generated by the GitHub Actions sync workflow) and
// populates the home page image and/or the gallery carousel, depending
// on which elements exist on the current page.

(async function () {
  let data = { homePagePic: null, gallery: [] };

  try {
    // Cache-bust so a freshly committed photos.json is picked up on reload
    const resp = await fetch("photos.json?v=" + Date.now());
    if (resp.ok) {
      data = await resp.json();
    }
  } catch (err) {
    console.error("Could not load photos.json:", err);
  }

  // ---- Home page picture ----
  const homePic = document.getElementById("home-pic");
  if (homePic && data.homePagePic) {
    homePic.src = data.homePagePic;
    homePic.hidden = false;
  }

  // ---- Gallery carousel ----
  const carousel = document.getElementById("carousel");
  if (carousel) {
    const photos = Array.isArray(data.gallery) ? data.gallery : [];
    const emptyMsg = document.getElementById("carousel-empty");

    if (photos.length === 0) {
      if (emptyMsg) emptyMsg.hidden = false;
      return;
    }

    const img = document.getElementById("carousel-img");
    const counter = document.getElementById("carousel-counter");
    let index = 0;

    function show(i) {
      index = (i + photos.length) % photos.length; // wrap around
      img.src = photos[index];
      counter.textContent = " " + (index + 1) + " of " + photos.length + " ";
    }

    document.getElementById("carousel-prev")
      .addEventListener("click", () => show(index - 1));
    document.getElementById("carousel-next")
      .addEventListener("click", () => show(index + 1));

    carousel.hidden = false;
    show(0);
  }
})();
